
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author asus
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        //Connect();
    }
  
    
//          public void Connect()  
//   {
//       
//        try {
//            Class.forName("oracle.jdbc.OracleDriver");
//             con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","9113");
//             
//            
//        } catch (ClassNotFoundException | SQLException ex) {
//            Logger.getLogger(addtrain.class.getName()).log(Level.SEVERE, null, ex);
//        }          
//            
//        
//  }


    
public void login(){
        String username=Tuser.getText();
        String pwd=Tpass.getText();
        try{
              Class.forName("oracle.jdbc.OracleDriver");
              String url="jdbc:oracle:thin:@//localhost:1521/XE";
             Connection con=DriverManager.getConnection(url,"system","9113"); 
            
                    PreparedStatement pst=con.prepareStatement("select * from registration where username=? and password=?");
                    pst.setString(1,username);
                    pst.setString(2,pwd);
                    
                     ResultSet rs=pst.executeQuery();
                    
                    if(rs.next()){
                        
                        MainHome r=new MainHome();
                        r.setVisible(true);
                         this.dispose();
                    }else
                    {
                         JOptionPane.showMessageDialog(this, "Incorrect Username or Password!"); 
                    }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tuser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tpass = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Login Application");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 337, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("Username:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 141, 40));
        getContentPane().add(Tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 256, 32));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 255));
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 141, 32));
        getContentPane().add(Tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 256, 32));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, 139, 50));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Login");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 560, 145, 50));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 560, 110, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Registration r=new Registration();        // TODO add your handling code here:

        r.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

       
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             login();

//         String tu=Tuser.getText();
//        String ps=Tpass.getText();
//        if(Tuser.getText().isEmpty()|| Tpass.getText().isEmpty())
//        {
//            JOptionPane.showMessageDialog(this,"Enter Your Username Or Password ");
//        }
////        else if(Tuser.getText().contains("rahul12")||Tpass.getText().contains("2323")){
////            new MainHome().setVisible(true);
////            this.dispose();
//        else {
//                    if(Tuser.getText().isEmpty()|| Tpass.getText().isEmpty())
//        {
//            JOptionPane.showMessageDialog(this,"Enter Your Username Or Password ");
//        }
//        else{
//
//            if(Tuser.getText().isEmpty()|| Tpass.getText().isEmpty())
//        {
//            JOptionPane.showMessageDialog(this,"Enter Your Username Or Password ");
//        }
//        else{
//
//            String Query ="select * from   registration where username='"+Tuser.getText()+"' and password='"+Tpass.getText()+"'";
//            try {
//                
//                pst=con.prepareStatement(Query);
//
//                rst=pst.executeQuery();
//                if(rst.next()){
//                    new MainHome().setVisible(true);
//                    this.dispose();
//                }
//                else
//                {
//                    JOptionPane.showMessageDialog(this,"Wrong Username or Password");
//                }
//            } catch (SQLException e) {
//                JOptionPane.showMessageDialog(this, e);
//            }
//        }
//                    } 
//
//        }

        
//            try {
//               
// Class.forName("oracle.jdbc.OracleDriver");
    //      con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","9113");
             
//                pst=con.prepareStatement("select * from registration where username=? and password=?");
//                pst.setString(1, tu);  
//                pst.setString(2, ps);
//                rst=pst.executeQuery();
//                if(rst.next()){
//                    new MainHome().setVisible(true);
//                    this.dispose();
//                }
                
               
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Tpass;
    private javax.swing.JTextField Tuser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
